# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labelUiPython.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Label(object):
    def setupUi(self, Label):
        Label.setObjectName("Label")
        Label.resize(1124, 692)
        Label.setStyleSheet("background-color: rgb(60, 59, 55);")
        self.centralwidget = QtWidgets.QWidget(Label)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.linPath = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.linPath.sizePolicy().hasHeightForWidth())
        self.linPath.setSizePolicy(sizePolicy)
        self.linPath.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.linPath.setStyleSheet("color: rgb(255, 255, 255);")
        self.linPath.setInputMask("")
        self.linPath.setText("")
        self.linPath.setObjectName("linPath")
        self.verticalLayout.addWidget(self.linPath)
        self.treeFolder = QtWidgets.QTreeWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeFolder.sizePolicy().hasHeightForWidth())
        self.treeFolder.setSizePolicy(sizePolicy)
        self.treeFolder.setStyleSheet("background-color: rgb(60, 59, 55);\n"
"selection-background-color: rgb(23, 4, 4);\n"
"selection-color: rgb(33, 29, 14);\n"
"color: rgb(255, 255, 255);")
        self.treeFolder.setObjectName("treeFolder")
        self.treeFolder.header().setVisible(True)
        self.verticalLayout.addWidget(self.treeFolder)
        self.console = QtWidgets.QTextEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setStyleSheet("color: rgb(255, 255, 255);")
        self.console.setObjectName("console")
        self.verticalLayout.addWidget(self.console)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("background-color: rgb(60, 59, 55);\n"
"selection-color: rgb(99, 221, 212);\n"
"selection-background-color: rgb(60, 59, 55);")
        self.tabWidget.setObjectName("tabWidget")
        self.modifyBox = QtWidgets.QWidget()
        self.modifyBox.setObjectName("modifyBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.modifyBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget.addTab(self.modifyBox, "")
        self.modifyAll = QtWidgets.QWidget()
        self.modifyAll.setObjectName("modifyAll")
        self.tabWidget.addTab(self.modifyAll, "")
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout_4.addWidget(self.widget)
        Label.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Label)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Label.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Label)
        self.statusbar.setObjectName("statusbar")
        Label.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Label)
        self.actionOpen.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Label)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(Label)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Label)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Label)

    def retranslateUi(self, Label):
        _translate = QtCore.QCoreApplication.translate
        Label.setWindowTitle(_translate("Label", "MainWindow"))
        self.linPath.setToolTip(_translate("Label", "<html><head/><body><p><br/></p></body></html>"))
        self.linPath.setWhatsThis(_translate("Label", "<html><head/><body><p>Path of foloder</p></body></html>"))
        self.linPath.setPlaceholderText(_translate("Label", "path to folder"))
        self.treeFolder.headerItem().setText(0, _translate("Label", "Folder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modifyBox), _translate("Label", "Modify Box"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modifyAll), _translate("Label", "Modify All of Images"))
        self.menuFile.setTitle(_translate("Label", "File"))
        self.menuEdit.setTitle(_translate("Label", "Edit"))
        self.actionOpen.setText(_translate("Label", "Open"))
        self.actionOpen.setShortcut(_translate("Label", "Ctrl+O"))
        self.actionSave.setText(_translate("Label", "Save"))
        self.actionSave.setShortcut(_translate("Label", "Ctrl+S"))
        self.actionQuit.setText(_translate("Label", "Quit"))
        self.actionQuit.setShortcut(_translate("Label", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Label = QtWidgets.QMainWindow()
    ui = Ui_Label()
    ui.setupUi(Label)
    Label.show()
    sys.exit(app.exec_())

